### PR TITLE
SignUp page form structure

### LINKED ISSUE #48: Implement the Signup Page form structure
**Task Title**
Implement the Signup Page form structure

**Task Description**
Create the structure of the Signup Page form, including all the required input fields and buttons.

**Subtasks**

1. Create a form for user registration on the Signup Page.

2. Include the following input fields in the form:
- Name
- Surname
- Email Address
- School Name
- Password
- Confirm Password

3. Implement a "Sign Up" button for user registration using #10 

4. import social sign-up buttons component for signing up with Google, Facebook, and Twitter.

5. Add a "Sign In" button that redirects users to the Sign In page if they already have an account.

### PR DESCRIPTION
**Pull request by Ben-Tewfik**
### Description
This pull request includes the following key enhancements to the Signup Page:

- Added the structure for the Signup Page form, including all the required input fields and buttons.
- Implemented user registration functionality with Firebase Authentication, allowing users to create accounts securely.
- Added essential validations during the registration process.

### Subtasks Completed
- Created a form for user registration on the Signup Page.
- Included the following input fields in the form:
  - Name
  - Surname
  - Email Address
  - School Name
  - Password
  - Confirm Password
- Implemented a "Sign Up" button for user registration using the Button Component #10.
- Added social sign-up buttons for signing up with Google, Facebook, and Twitter.
- Included a "Sign In" button that redirects users to the Sign In page if they already have an account.
- Add Form validation

# Related Issue

- Resolve #48

### CODE REVIEW

**Review by KatiaGhezali — APPROVED** [review]
I have just finished testing it Tewfik and I might say, it works smoothly 💯
Amazing work 🚀

**Review by hocine1212 — COMMENTED** [review]
I appreciate the effective utilization of regular expressions for validation in the code, good job Tewfik 👏

**Review by hocine1212 — APPROVED** [review]
I appreciate the effective utilization of regular expressions for validation in the code, good job Tewfik 👏

**Review by khaoulasara — APPROVED** [review]
Excellent job on this pull request! 🌟 The sign-in feature looks solid, and I appreciate your dedication to enhancing the user experience.

**Pull request merged**
