### PR TITLE
Filter Products Component

### LINKED ISSUE #114: Filter Products component
**Title**
Create a Filter component for the products page.

**Description**
Create a filter component to filter products based on categories, price range, and Type borrow or sale.

**Subtasks**

- [x]  Create the basic structure of the Filter component.

- [x]  Implement a price range filter that allows users to specify a minimum and maximum price.

- [x]  Implement a type filter that allows users to choose between borrowing or buying/selling products.

- [x]  Implement a category filter that allows users to select one or multiple categories.

- [x]  Implement a Condition filter that allows users to select one or multiple conditions of the product like new good poor.

- [x] Translate filter component into french and Arabic

- [x] Style the filter component and test the responsiveness into multiple screens.

### PR DESCRIPTION
**Pull request by Ben-Tewfik**
## Description

This pull request introduces a new `Filter` component for the products page. The `Filter` component allows users to filter products based on categories, price range, type (borrow or sale), and condition.

## Changes Made

- Created the `Filter` component with the specified functionalities.
- Implemented the price range, type, category, and condition filters.
- Added translations for French and Arabic.
- Styled the `Filter` component for a visually appealing design.
- Tested the responsiveness on various screen sizes.

### Screenshots
**Desktop**
image
**Tablet**
image
**Mobile**
image

# Related Issue

- Resolve #114

### CODE REVIEW

**Review by KatiaGhezali — APPROVED** [review]
Amazing work Tewfik, Approved!

**Review by khaoulasara — APPROVED** [review]
Great work on this pull request! The addition of the Filter component for the products page is a valuable enhancement. The subtasks cover a comprehensive set of functionalities, from basic structure to language translation and styling. This will undoubtedly improve the user experience and make the product page more versatile. Thumbs up! 👍

**Review by hocine1212 — APPROVED** [review]
I tested the filter and it's working perfectly . Nice work

**Comment by samiba6** [comment]
Well Done !

**Pull request merged**
