### PR TITLE
Footer

### LINKED ISSUE #12: Footer
**Task title**
Footer Responsiveness and Design Styling

**Task description**
The footer component of our project requires improvements in terms of responsiveness and design styling to ensure it displays correctly and looks visually appealing on different devices and screen sizes.

**Subtasks**

- [x] Ensure the footer is responsive for mobile devices.

- [x]  Adjust font size and spacing for better readability.

- [x] Apply brand colors and styling to the footer.

- [x] Add test for the footer component.

- [x] Implement the links for a swift navigation between the pages.

**Screenshots**
Put at least one screenshot here
Desktop :
desktop

Tablet :
tablet

Mobile :
mobile

**Link to the component on Figma**
Put the link here
Desk top version:
https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=123-14088&mode=design&t=A1Bfa7VVZuoc9XKV-4
Tablet version :
https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=201-14740&mode=design&t=A1Bfa7VVZuoc9XKV-4
Mobile version :
https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=213-16001&mode=design&t=A1Bfa7VVZuoc9XKV-4

### PR DESCRIPTION
**Pull request by khaoulasara**
### **Footer Responsiveness and Design Styling**
Fixes #12

**Description:**

Hello Team,

I'm pleased to present the changes made to improve the responsiveness and design styling of our project's footer. These enhancements are aimed at ensuring a visually appealing and correctly displayed footer on various devices and screen sizes. Here's an overview of the work I've completed:

**Tasks Completed:**

- [x] Mobile Responsiveness: The footer has been updated to ensure proper responsiveness on mobile devices. It now adapts smoothly to varying screen sizes, enhancing the overall user experience.
- [x] Font Size and Spacing Adjustment: I've adjusted the font size and spacing to improve readability. This ensures that the content in the footer is more accessible and visually pleasing.
- [x]  Brand Colors and Styling: Brand colors and styling have been applied to the footer, creating a cohesive and branded look that aligns with the project's design guidelines.
- [x] Links Implementation: For a better user experience, I've implemented links within the footer to connect users to relevant pages and sections of our project. These links provide easy navigation and access to important content.
- [x] Footer Testing: Rigorous testing has been carried out to verify the correct functionality of the footer, ensuring that all links work as intended and the design is consistent across various devices.

**Screenshots:**

Desktop:
desktop

Tablet:
tablet

Mobile:
mobile

**Figma Link:**

Desktop version: https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=123-14088&mode=design&t=A1Bfa7VVZuoc9XKV-4

Tablet version: https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=201-14740&mode=design&t=A1Bfa7VVZuoc9XKV-4

Mobile version: https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=213-16001&mode=design&t=A1Bfa7VVZuoc9XKV-4

Please review the changes and provide your feedback.

**Next Steps:**

I'm looking forward to merging these improvements into our project and continuing to enhance our user experience. Your collaboration and support are highly valued.

Thank you for your time.

@khaoulasara 

**Related Issue:**
Footer Responsiveness and Design Styling #12

# Related Issue

- Resolve #12

### CODE REVIEW

**Review by hocine1212 — CHANGES_REQUESTED** [review]
It would be best if you change  the color of the contact us section to another color  from the color palette‏‏.
I would suggest this one F1F6FA‏‏.‏‏

**Comment by Ben-Tewfik** [comment]
@hocine1212  it appears that @khaoulasara is having technical issues and since the footer is ready we should merge it.

**Comment by hocine1212** [comment]
> It would be best if you change the color of the contact us section to another color from the color palette‏‏. I would suggest this one F1F6FA‏‏.‏‏



> @hocine1212 it appears that @khaoulasara is having technical issues and since the footer is ready we should merge it.

Thank you @Ben-Tewfik

**Review by hocine1212 — APPROVED** [review]

**Review by Ben-Tewfik — APPROVED** [review]
Great Job thank you for your hard effort.

**Pull request merged**
