### PR TITLE
Searchbar functionality and Loader component

### LINKED ISSUE #144: Searchbar functionality
**Task title**
Search bar functionality

**Task description**
Add a dynamic link to the search bar that takes the user directly to the single product page.

### LINKED ISSUE #149: Create Loader component
**Task Title**
Create Loader Component

**Task Description**
Summary:
Implement a reusable loader component using the React Spinners library to enhance the user experience during loading or asynchronous operations.

Details:
Create a new React component named Loader that incorporates the GridLoader from the React Spinners library.
The loader component should be centered on the screen, ensuring a pleasant visual experience.
Allow customization of the loader size and color through props.

### PR DESCRIPTION
**Pull request by Ben-Tewfik**
## Description
This pull request introduces two significant enhancements to the application:

**Loader Component:**
Implemented a new Loader component using the GridLoader from the React Spinners library.
Ensured that the loader is centered on the screen for a pleasant visual experience.
Added customization options for the loader size and color through props.

**Search Bar Functionality:**
Added dynamic link functionality to the search bar.
When a user enters a query and clicks search, they are now directed to the single product page related to the search.

## Screenshot
image
image

# Related Issue
- Resolve #144
- Resolve #149

### CODE REVIEW

**Review by MouniaBelkheir — APPROVED** [review]
You took good care of the details, nice job Tewfik

**Review by hocine1212 — CHANGES_REQUESTED** [review]
I've tested the code and  I appreciate the addition of the other category. Everything functions as expected. However, I noticed that the styling in the search bar could be enhanced with a hover effect. Adding a hover effect to the search results would improve the user experience, allowing users to easily identify the result they are hovering over.

**Comment by Ben-Tewfik** [comment]
> I've tested the code and I appreciate the addition of the other category. Everything functions as expected. However, I noticed that the styling in the search bar could be enhanced with a hover effect. Adding a hover effect to the search results would improve the user experience, allowing users to easily identify the result they are hovering over.

Thanks For your feedback I will enhance the styling.

**Review by hocine1212 — APPROVED** [review]

**Comment by hocine1212** [comment]
> > I've tested the code and I appreciate the addition of the other category. Everything functions as expected. However, I noticed that the styling in the search bar could be enhanced with a hover effect. Adding a hover effect to the search results would improve the user experience, allowing users to easily identify the result they are hovering over.
> 
> Thanks For your feedback I will enhance the styling.

 It's looking better now nice work tewfik

**Pull request merged**
