### PR TITLE
Faq Component

### LINKED ISSUE #169: Style the Faq component
**Task Title:**
Style the FAQ Component

**Task Description:**
The FAQ component on our website requires styling improvements to enhance its visual appeal and user experience. This task involves applying styles to the FAQ section to make it more cohesive with our overall design and ensure it aligns with our brand identity.

### PR DESCRIPTION
**Pull request by Ben-Tewfik**
## Pull Request Description:
This pull request addresses the styling improvements needed for the FAQ component on our website. The changes aim to enhance the visual appeal and user experience, ensuring a cohesive design aligned with our brand identity.

## Changes Made:
Changed the question and answers 
Adjusted translation for better readability.
Ensured responsive design for optimal viewing on various devices.

## Screenshots
image

# Related Issue

- Resolve #169

### CODE REVIEW

**Review by KatiaGhezali — CHANGES_REQUESTED** [review]
The code is clean and works smoothly, however I did notice that the translations are not always spot on such as: "place de marché" in french . Please take a look at them.

**Comment by Ben-Tewfik** [comment]
> The code is clean and works smoothly, however I did notice that the translations are not always spot on such as: "place de marché" in french . Please take a look at them.

Thanks for your feedback I will change the translation

**Review by KatiaGhezali — APPROVED** [review]
Thank you for making the necessary changes Tewfik, it looks nice.

**Review by hocine1212 — APPROVED** [review]
I like the styling of faq component .Well done!

**Pull request merged**
