### PR TITLE
Navbar Component

### LINKED ISSUE #20: NavBar
**Task title**
 Create NavBar component

**Task description**
Create a responsive and visually appealing navigation bar (navbar) for the Student Store website. The navbar should be designed to enhance user experience and facilitate easy navigation throughout the site.

Navbar Elements:

The navbar should include the following elements:

The Logo of the website.

Home: A link that takes users to the website's home page.

Donation: A link that allows users to make donations or contributions to a cause or organization.

About Us: A link that provides information about the organization or website.

Search Bar: Develop a search bar component that allows users to search for content or information within the website. The search bar should provide real-time search suggestions and an intuitive search experience.

Language Translation Dropdown: Integrate a language translation dropdown menu that enables users to switch between different languages for website content. The dropdown should support Arabic, French, and English, providing a seamless translation experience.

Shopping Cart: A symbol or link that indicates the number of items in the user's shopping cart. It should provide access to the user's cart for online shopping.

Profile DropDown: create a user profile dropdown with account management options such as profile settings, sign out, and user preferences.

Underbar Categories: The underbar should contain 9 categories, which can include links to various sections or content on the website. These categories should be relevant to the website's content and user navigation needs.

**Subtasks**

- [x] #14 
- [x] #36 
- [x] #15 
- [x] #16 
- [x] Create Logo component
- [x] Create navigation Links and the Cart button 
- [ ] Add styling to the Navbar

**Screenshots**
image

**Link to the component on Figma**
[Navbar link on Figma](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2704-5051&mode=design&t=h4uem3Nc0kLCjqla-4)

### PR DESCRIPTION
**Pull request by MouniaBelkheir**
Created the Logo and the navbar components with their tests, the Navbar is responsive in large  and small screens, the UnderBar is appearing only in the small screens

##Screenshots:
image

navbar mobile v

# Related Issue

- Resolve #20

### CODE REVIEW

**Review by KatiaGhezali — CHANGES_REQUESTED** [review]
I have checked the navigation bar component, and I believe there is a link missing.
Please add the "products" link.

**Comment by Ben-Tewfik** [comment]
> I have checked the navigation bar component, and I believe there is a link missing. Please add the "products" link.

Hello @KatiaGhezali, I noticed that the missing link you mentioned is indeed absent. As @MouniaBelkheir is not feeling well, I kindly request your approval for the changes and to mark this as resolved. This will allow us to merge the PR, and we can continue to make improvements later.

**Comment by KatiaGhezali** [comment]
@Ben-Tewfik I see, I will approve of the current work, as I find it well done and we can fix any problem later on.

**Review by KatiaGhezali — APPROVED** [review]
Work well done Mounia.

**Review by khaoulasara — APPROVED** [review]
Looks good, please merge! Well done on the Navbar Component .

**Pull request merged**
