### PR TITLE
Fix product details issue

### LINKED ISSUE #32: ProductDetails.
### **Task title**

Create Product Details Component

 ### **Task description**
Implement a new component in the Single Product page to display detailed information about a product. The component should include product images, name, price, condition, description, seller/borrower information, and  the product's location.

### **Subtasks**

**Component Creation:**

- [x] Create a new React component named ProductDetails.
- [x] Design the component layout to include sections for product images, name, price, condition, description and seller/borrower information.

 **Data Integration:**

- [x]  Fetch product data from Firebase Firestore database.
- [x]  Structure the Firebase database to include fields for images URLs, product name, price, condition, description, seller/borrower details (name, contact information), and location coordinates.

 **Image Display:**

- [x]  Display product images from the fetched data in a visually appealing manner. Using a grid layout for multiple images.

 **Text Information:**

- [x]  Display the product name, price, and condition from the fetched data prominently.
- [x]  Include a section for the product description from the fetched data.

 **Seller/Borrower Information:**

- [x]  Display the name and contact information of the person selling or lending the product fetched from Firebase.

 **Responsive Design:**

- [x]  Ensure the layout is responsive and adapts well to various screen sizes, including mobile devices and tablets.

 **CSS Styling:**

- [x]  Apply CSS styles to enhance the visual appeal of the page.

 **Testing:**

- [x]  Test the page thoroughly to ensure all elements are displayed correctly, and the map integration works as expected with data fetched from Firebase.
- [x] Address any responsive design issues on different devices and screen sizes.

### **Screenshots**
image

### **Link to the component on Figma**
[The Product Details Component On Figma](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=120-11066&mode=design&t=B0s8cYWWr0AAdI1k-4)

### LINKED ISSUE #81: Fix product details issue
### **Task title**

Create Product Details Component

 ### **Task description**
Implement a new component in the Single Product page to display detailed information about a product. The component should include product images, name, price, condition, description, seller/borrower information, and  the product's location.

### **Subtasks**

**Component Creation:**

- [x] Create a new React component named ProductDetails.
- [x] Design the component layout to include sections for product images, name, price, condition, description and seller/borrower information.

 **Data Integration:**

- [x]  Fetch product data from Firebase Firestore database.
- [x]  Structure the Firebase database to include fields for images URLs, product name, price, condition, description, seller/borrower details (name, contact information), and location coordinates.

 **Image Display:**

- [x]  Display product images from the fetched data in a visually appealing manner. Using a grid layout for multiple images.

 **Text Information:**

- [x]  Display the product name, price, and condition from the fetched data prominently.
- [x]  Include a section for the product description from the fetched data.

 **Seller/Borrower Information:**

- [x]  Display the name and contact information of the person selling or lending the product fetched from Firebase.

 **Responsive Design:**

- [x]  Ensure the layout is responsive and adapts well to various screen sizes, including mobile devices and tablets.

 **CSS Styling:**

- [x]  Apply CSS styles to enhance the visual appeal of the page.

 **Testing:**

- [x]  Test the page thoroughly to ensure all elements are displayed correctly, and the map integration works as expected with data fetched from Firebase.
- [x] Address any responsive design issues on different devices and screen sizes.

**Fix issue:**
#32
### **Screenshots**
image

### **Link to the component on Figma**
[The Product Details Component On Figma](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=120-11066&mode=design&t=B0s8cYWWr0AAdI1k-4)

### PR DESCRIPTION
**Pull request by KatiaGhezali**
### **Pull Request Title:**
Add Responsive Product Details Component

### **Pull Request Description:**

**Changes Made:**

- Created a responsive product details component displaying product and user information.

- Fetched product data from Firebase and displayed it dynamically.

- Styled the components elements for a clean and responsive layout.

- Tested the component using snapshot tests.

**Purpose:**
The purpose of this pull request is to add a responsive product details component that fetches data from Firebase, allowing users to view product details seamlessly across different devices. The layout has been optimized for various screen sizes, ensuring a consistent user experience.

### **Screenshots :**
- Large screens:

image

- Medium screens:

image

- Small screens:

image

### **Additional Notes:**

- Used Next.js and Firebase for efficient data fetching and rendering.

- Ensured the code adheres to best practices and is well-commented for readability.

- Created snapshot tests to validate the layout across different screen sizes.

### **Checklist:**

- [x]  Implemented responsive design for the product details page.

- [x]  Fetched and displayed product data dynamically from Firebase.

- [x]  Styled the page elements using Tailwind CSS for a polished look.

- [x]  Added snapshot tests to validate the responsiveness of the page.

# Related Issue

- Resolve #81 
- Resolve #32

### CODE REVIEW

**Review by Ben-Tewfik — CHANGES_REQUESTED** [review]
Firebase is working it is fetching the the product and user info Great job for that
I tested the reponsiveniss in the medium screen and it needs some modifications

**Comment by KatiaGhezali** [comment]
Thank you for bringing my attention to that @Ben-Tewfik, I will work on it.

**Comment by KatiaGhezali** [comment]
@Ben-Tewfik I have just fixed the issues, I would appreciate if you check them again.

**Review by Ben-Tewfik — APPROVED** [review]

**Review by hocine1212 — APPROVED** [review]
Great work on refining the page design and successfully resolving the conflict!

**Pull request merged**
