### PR TITLE
Create dropdown component 

### LINKED ISSUE #14: ProfileDropDown
**Task title**
ProfileDropDown

**Task description**
Develop a profile dropdown component that offers easy access to key links such as user profile, listings, and the option to log out, utilizing daisyUI and tailwind.

**Subtasks**
Put the subtasks here if any (optional)

**Screenshots**
image

**Link to the component on Figma**
[Link to the component on Figma](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2436-2321&mode=design&t=Bpp5tZklltAgrzyj-4)

### PR DESCRIPTION
**Pull request by hocine1212**
In this pull request I created a new `ProfileDropdown` component and i did the following : 

- Added links to user profile and listings.
- Added a log-out option.
- Used daisyUI and Tailwind for styling.
 # Screenshot:
Screenshot 2023-10-20 004423

fix #14

### CODE REVIEW

**Review by KatiaGhezali — APPROVED** [review]
Good job Hocine ✅

**Review by khaoulasara — APPROVED** [review]
Kudos on the dropdown component! 🙌 This is a significant enhancement to our project. I can see the attention to detail in its design and functionality. It's going to make a positive impact on the user experience. Great job, team!

**Review by samiba6 — APPROVED** [review]
Well done, keep up the good work.

**Review by MouniaBelkheir — APPROVED** [review]
Well done Hocine

**Pull request merged**
